/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DeparturePointListRelationFilter } from "../../departurePoint/base/DeparturePointListRelationFilter";
import { EntryPointListRelationFilter } from "../../entryPoint/base/EntryPointListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { RegionListRelationFilter } from "../../region/base/RegionListRelationFilter";

@InputType()
class CountryWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  code?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => DeparturePointListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeparturePointListRelationFilter)
  @IsOptional()
  @Field(() => DeparturePointListRelationFilter, {
    nullable: true,
  })
  departurePoints?: DeparturePointListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => EntryPointListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EntryPointListRelationFilter)
  @IsOptional()
  @Field(() => EntryPointListRelationFilter, {
    nullable: true,
  })
  entryPoints?: EntryPointListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  population?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RegionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RegionListRelationFilter)
  @IsOptional()
  @Field(() => RegionListRelationFilter, {
    nullable: true,
  })
  regions?: RegionListRelationFilter;
}

export { CountryWhereInput as CountryWhereInput };
